#########################################################################
# Title:         Pre-Tasks: Variables Task                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/Cloudbox/Community                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Variables | Set 'nzbs_downloads_path' variable"
  set_fact:
    nzbs_downloads_path:
      - "{{ downloads.nzbs }}:/downloads/nzbs"
  when: not (
        (downloads is undefined)
        or
        (downloads is none)
        or
        (downloads | trim | length == 0)
        or
        (downloads.nzbs is undefined)
        or
        (downloads.nzbs is none)
        or
        (downloads.nzbs | trim | length == 0)
      )

- name: "Variables | Set 'torrents_downloads_path' variable"
  set_fact:
    torrents_downloads_path:
      - "{{ downloads.torrents }}:/downloads/torrents"
  when: not (
        (downloads is undefined)
        or
        (downloads is none)
        or
        (downloads | trim | length == 0)
        or
        (downloads.torrents is undefined)
        or
        (downloads.torrents is none)
        or
        (downloads.torrents | trim | length == 0)
      )
