#########################################################################
# Title:         Cloudbox Community: Settings | Ansible Config          #
# Author(s):     l3uddz, desimaniac, Migz93                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if '{{ item }}' exists."
  stat:
    path: "{{ playbook_dir }}/{{ item }}"
  register: file

- name: "Copy '{{ item }}.default' to '{{ item }}'."
  copy:
    src: "{{ playbook_dir }}/defaults/{{ item }}.default"
    dest: "{{ playbook_dir }}/{{ item }}"
    owner: "{{ community_yml.stat.uid }}"
    group: "{{ community_yml.stat.gid }}"
    mode: 0664
    force: yes
  when: not file.stat.exists

- name: Add 'roles_path' to '{{ item }}'
  ini_file:
    path: "{{ playbook_dir }}/{{ item }}"
    section: defaults
    option: roles_path
    value: "roles:$HOME/cloudbox/roles:$HOME/cloudbox/resources/roles"
    state: present
  when: file.stat.exists

- name: Add 'hash_behaviour' to '{{ item }}'
  ini_file:
    path: "{{ playbook_dir }}/{{ item }}"
    section: defaults
    option: hash_behaviour
    value: merge
    state: present
  when: file.stat.exists
